# Generated by Django 4.2 on 2024-05-13 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EIAHourlyDataCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cached_date', models.DateTimeField(verbose_name='date cached')),
                ('url_segment', models.CharField(max_length=200)),
                ('ba', models.CharField(max_length=32)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('json_response_blob', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HourlyGenerationMixCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generation_mwh', models.FloatField()),
                ('emitted_tons_co2', models.FloatField()),
                ('fuel_type', models.CharField(max_length=16)),
                ('timestamp', models.DateTimeField()),
                ('generating_ba', models.CharField(max_length=32)),
                ('consuming_ba', models.CharField(max_length=32)),
            ],
        ),
    ]
