# Generated by Django 4.2 on 2024-05-13 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('load_shifting', '0001_cache_tables_first_try'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eiahourlydatacache',
            old_name='json_response_blob',
            new_name='response_csv',
        ),
        migrations.RemoveField(
            model_name='eiahourlydatacache',
            name='ba',
        ),
        migrations.AddField(
            model_name='eiahourlydatacache',
            name='facets',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
