# Generated by Django 4.2 on 2024-05-16 21:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('load_shifting', '0002_cache_tables_use_csv'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hourlygenerationmixcache',
            old_name='consuming_ba',
            new_name='ba_name',
        ),
        migrations.RemoveField(
            model_name='hourlygenerationmixcache',
            name='emitted_tons_co2',
        ),
        migrations.RemoveField(
            model_name='hourlygenerationmixcache',
            name='fuel_type',
        ),
        migrations.RemoveField(
            model_name='hourlygenerationmixcache',
            name='generating_ba',
        ),
        migrations.RemoveField(
            model_name='hourlygenerationmixcache',
            name='generation_mwh',
        ),
        migrations.RemoveField(
            model_name='hourlygenerationmixcache',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='hourlygenerationmixcache',
            name='cached_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 16, 21, 7, 8, 916850), verbose_name='date cached'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hourlygenerationmixcache',
            name='calculated_csv',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hourlygenerationmixcache',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 16, 21, 7, 30, 745180)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hourlygenerationmixcache',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 16, 21, 7, 52, 639514)),
            preserve_default=False,
        ),
    ]
