# Generated by Django 4.2 on 2024-05-20 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('load_shifting', '0004_all_purpose_cache'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EIAHourlyDataCache',
        ),
        migrations.DeleteModel(
            name='HourlyGenerationMixCache',
        ),
    ]
